app:
  port: 3000
  corsEnabled: true
  corsAllowedOrigins: <list of allowed origins>
  jwtSecret: <256 bit jwt secret>
db:
  postgres:
    host: localhost
    port: 5432
    username: <username>
    password: <password>
    databaseName: worksat
  synchronize: true
